### ISSUE TITLE
Using different language dataset is also available?

### ISSUE THREAD

**Issue by haloha123** [RF5/transfusion-asr#1]
Your work is excellent!

I have a dataset in Chinese, I am wondering using Chinese dataset is also workable with the code?

Thank you!

**Comment by RF5** [comment]
Yes, it should definitely be possible to use a chinese dataset. I have not tried it before, so one or two small things might need tweaking, but generally it should work -- the main thing you likely need to update is the vocabulary used for the Chinese dataset. 

Hope your training goes well!

**Comment by haloha123** [comment]
May I ask which part of code can I change the vocabulary? 

Thank you!

**Comment by RF5** [comment]
The vocab is constructed in the `split_data.py` preprocessing script, namely [this function](https://github.com/RF5/transfusion-asr/blob/master/split_data.py#L52) . You would just need to edit that to construct the Chinese vocabulary you desire.

**Comment by haloha123** [comment]
Thank you for your reply! I will try it~

**Comment by RF5** [comment]
Thaanks, good luck!

**Comment by haloha123** [comment]
Hi, thank you for your advice.
Now, I use Chinese vocab, and the number of vocab is big. It is different from English.
So it will cause a size mismatch.

`size mismatch for char_embedding.weight: copying a param with shape torch.Size([29, 768]) from checkpoint, the shape in current model is torch.Size([2163, 768]).`

`size mismatch for head.1.weight: copying a param with shape torch.Size([29, 768]) from checkpoint, the shape in current model is torch.Size([2163, 768]).`

`size mismatch for head.1.bias: copying a param with shape torch.Size([29]) from checkpoint, the shape in current model is torch.Size([2163]).`

How to solve it? Thank you very much!

**Comment by RF5** [comment]
You are trying to resume training of a English model with a Chinese vocabulary. This will not work. If you wish to use a Chinese vocabulary you will need to train from scratch and not attempt to load the existing English checkpoints. 

Hope that helps!

**Comment by haloha123** [comment]
Thank you! I will try it!
