### ISSUE TITLE
How can I do inference with input a wav file

### ISSUE THREAD

**Issue by haloha123** [RF5/transfusion-asr#2]
Thank you for proposing this work. 

In my case, I want to print out the predicted transcript of my utterance, but it seems that the inference time is quite long. It is about 30 sec per wav file by using GPU. How can I shorten the inference time? 

Thank you!

**Comment by RF5** [comment]
Sure thing -- it is on the readme [here](https://github.com/RF5/transfusion-asr/blob/master/README.md#quickstart) . It explains how to perform inference, and the inference code is stored in the [file here](https://github.com/RF5/transfusion-asr/blob/master/transfusion/score.py)

**Comment by haloha123** [comment]
it seems that the inference time is quite long. It is about 30 sec per wav file by using GPU. How can I shorten the inference time?

Thank you!

**Comment by RF5** [comment]
Hi, I am not certain how you can shorten the inference time, there are several ways. You can either try tweaking the settings in the DSH config in score.py to use less computation (see paper for how the parameters relate to computation usage), or you can try implement various int 4 or int 8 quantization methods for inference, or you can even try implementing some of the existing techniques in the literature for skipping certain diffusion steps -- however we do not have that in this repository.  You can also try using a faster GPU which will reduce the inference time as well.

Hope that helps.

**Comment by haloha123** [comment]
Ya, thank you! I will try the method you provided~
