### ISSUE TITLE
How to fine tune the model with your provided checkpoint?

### ISSUE THREAD

**Issue by jellyfish1456** [RF5/transfusion-asr#3]
It is so happy to see your work and the performance is excellent!

Now I want to use your pretrained model checkpoint (transfusion_462k_slim.pt) to fine-tune the model with my own English dataset, not train from scratch. 

How can I do? 

Thank you!

**Comment by RF5** [comment]
Thanks for your interest. The `transfusion_462k_slim.pt` checkpoint is slimmed down to save space for inference and so it doesn't have the optimizer state dict, so it doens't permit fine-tuning. If you're interested in fine-tuning from the current checkpoint, I'll find the full untrimmed checkpoint and upload it in a few days, will post to this issue once it's up.

**Comment by jellyfish1456** [comment]
Thank you!
I am looking forward seeing the new untrimmed checkpoint!

**Comment by RF5** [comment]
I have updated the release with the full checkpoint with all optimizer states and configs. You can resume training from this checkpoint using the `resume_checkpoint=<path to parent folder of the full checkpoint>` cli argument in `train.py`. However, if you want to fine-tune it on a new dataset, depending on what you have changed the dataloading setup you might need to add `_, client_sd = model_engine.load_checkpoint(cfg.checkpoint_path, <path to parent folder where the ckpt is stored> )`  at an appropriate place in `train.py`.

See the new bullet point and files in https://github.com/RF5/transfusion-asr/releases/tag/v1.0 for info on downloading the full float32 checkpoint. I hope this helps!

**Comment by jellyfish1456** [comment]
May I ask that the max_steps should be modified as well?
Because if I try the max step lower than 4_000_000, it will show Training completed directly

![螢幕擷取畫面 2023-03-27 203928](https://user-images.githubusercontent.com/38533075/227943182-d92c08d4-d68d-43e5-af9a-4cef0eb471f7.png)

**Comment by RF5** [comment]
Ahh yes, you are correct, you may need to increase the maximum number of training steps, best is likely to make it just a massive number and then stop training as needed. E.g. in the training cli set the max step to `999_000_000` or similar.

**Comment by jellyfish1456** [comment]
Thank you! I will try to fine-tune it now~

Sorry to interrupt. There is another question, if I finish fine-tuning the model, how can I like you to trimmed the full checkpoint to become like "transfusion_462k_slim.pt" to lower the inference time?

Thank you very much!

**Comment by RF5** [comment]
Simply load the raw checkpoint in torch (e.g. with `torch.load`), then delete the keys for optimizer and other unused keys not related to the actual model state dict. Then save the checkpoint again with those keys deleted. The newly saved checkpoint should be much smaller.

Hope that helps

**Comment by RF5** [comment]
Closing for now, if there is another issue feel free to go ahead and reopen.

**Comment by jellyfish1456** [comment]
Thank you!
